### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by darkzone964** [anmolksachan/ThreatTracer#1]
Traceback (most recent call last):
  File "/home/parrot/Desktop/tools/ThreatTracer/threattracer.py", line 193, in <module>
    print(colored(f"Short Name: {result['Short Name']}", "light_blue"))
  File "/usr/lib/python3/dist-packages/termcolor.py", line 105, in colored
    text = fmt_str % (COLORS[color], text)
KeyError: 'light_blue'

**Comment by anmolksachan** [comment]
Can you try again we updated few things.
